version: 1.0.{build}

configuration:
- Release
- Debug

cache:
- psnova-texteditor\packages -> **\psnova-texteditor\psnova-texteditor\packages.config

before_build:
- cmd: nuget restore "psnova-texteditor/psnova-texteditor.sln"

after_build:
- cmd: git rev-parse --short %APPVEYOR_REPO_COMMIT%>%TMP%\gitshort.txt
- cmd: set /P GITSHORT=<%TMP%\gitshort.txt
- set BUILD_ARCHIVE=%APPVEYOR_REPO_BRANCH%-%GITSHORT%-%CONFIGURATION%-texteditor
- cmd: cd
- cmd: cd nova-texteditor/bin
- cmd: cd %CONFIGURATION%
- cmd: 7z a %BUILD_ARCHIVE% *.* -xr!.gitignore
- appveyor PushArtifact %BUILD_ARCHIVE%
- cmd: cd
- cmd: cd ../..
- set BUILD_ARCHIVE=%APPVEYOR_REPO_BRANCH%-%GITSHORT%-%CONFIGURATION%-textinserter.7z
- cmd: cd psnova-textinserter/bin
- cmd: cd %CONFIGURATION%
- cmd: 7z a %BUILD_ARCHIVE% *.* -xr!.gitignore
- appveyor PushArtifact %BUILD_ARCHIVE%
- cmd: cd ../../..

build:
  project: psnova-texteditor\psnova-texteditor.sln
  verbosity: quiet

